/*
 * invaders_config.h
 *
 *  Created on: 2015/09/04
 *      Author: minagawa-sho
 */

#ifndef INVADERS_CONFIG_H_
#define INVADERS_CONFIG_H_

/* Definitions for the entire game */
#define ERRORLOG_FILEPATH ("./invaders_error.log")
#define IDEAL_FRAME_TIME (1000L / 30L)
#define CANVAS_SIZE_X (36)
#define CANVAS_SIZE_Y (80)

/* Definitions for in-game entities */
#define PLAYER_JET_POSITION_X (CANVAS_SIZE_X - 6)
#define PLAYER_JET_START_POSITION_Y (7)
#define PLAYER_JET_SIZE_X (2)
#define PLAYER_JET_SIZE_Y (3)
#define PLAYER_BULLET_MOVING_INTERVAL (15L)
#define N_TOCHCAS (4)
#define N_TOCHCA_BLOCKS (36)
#define N_TOCHCA_BLOCKS_LAYOUT_X (4)
#define TOCHCA_POSITION_X (CANVAS_SIZE_X - 11)
#define TOCHCA_POSITION_Y (11)
#define TOCHCA_LAYOUT_INTERVAL_Y (16)
#define N_INVADERS (60)
#define N_INVADERS_LAYOUT_X (5)
#define N_INVADERS_LAYOUT_Y (N_INVADERS / N_INVADERS_LAYOUT_X)
#define INVADER_START_POSITION_X (4)
#define INVADER_START_POSITION_Y (11)
#define INVADER_SIZE_X (2)
#define INVADER_SIZE_Y (3)
#define INVADER_LAYOUT_INTERVAL_X (3)
#define INVADER_LAYOUT_INTERVAL_Y (5)
#define INVADER_INVASION_STEP_X (2)
#define INVADER_MOVING_RANGE_Y_MIN (4)
#define INVADER_MOVING_RANGE_Y_MAX (CANVAS_SIZE_Y - 5)
#define INVADER_MOVING_INTERVAL (1000L)
#define INVADER_SHOOTING_INTERVAL (700L)
#define COMMANDER_INVADER_START_POSITION_X (3)
#define COMMANDER_INVADER_START_POSITION_Y (INVADER_MOVING_RANGE_Y_MIN)
#define COMMANDER_INVADER_MOVING_INTERVAL (250L)
#define COMMANDER_INVADER_TURN_INTERVAL (20000L)
#define COMMANDER_INVADER_SCORE (100L)
#define SENIOR_INVADER_SCORE (30L)
#define YOUNG_INVADER_SCORE (20L)
#define LOOKIE_INVADER_SCORE (10L)
#define INVADER_INVASION_THRESHOLD_POSITION_X (PLAYER_JET_POSITION_X)
#define N_INVADER_BULLETS (20)
#define INVADER_BULLET_MOVING_INTERVAL (80L)

/* Definitions for meta AI */
#define LEVEL0_MOVE_SPEED (100)
#define LEVEL1_THRESHOLD (50)
#define LEVEL1_MOVE_SPEED (115)
#define LEVEL2_THRESHOLD (35)
#define LEVEL2_MOVE_SPEED (140)
#define LEVEL3_THRESHOLD (20)
#define LEVEL3_MOVE_SPEED (190)
#define LEVEL4_THRESHOLD (10)
#define LEVEL4_MOVE_SPEED (450)
#define LEVEL5_THRESHOLD (5)
#define LEVEL5_MOVE_SPEED (1000)
#define LEVEL6_THRESHOLD (2)
#define LEVEL6_MOVE_SPEED (2000)
#define LEVEL7_THRESHOLD (1)
#define LEVEL7_MOVE_SPEED (4000)

/* Definitions for HUD objects */
#define TITLE_TEXT ("THE INVADERS FROM GALAXY")
#define TITLE_POSITION_X (CANVAS_SIZE_X / 2)
#define TITLE_POSITION_Y (CANVAS_SIZE_Y / 2)
#define SCORE_INITIAL_VALUE (0L)
#define SCORE_POSITION_X (1)
#define SCORE_POSITION_Y (CANVAS_SIZE_Y - 6)
#define CREDIT_INITIAL_VALUE (2)
#define CREDIT_POSITION_X (CANVAS_SIZE_X - 2)
#define CREDIT_POSITION_Y (6)
#define GAME_CLEAR_CAPTION_TEXT ("GAME CLEAR")
#define GAME_OVER_CAPTION_TEXT ("GAME OVER")
#define EVENT_CAPTION_POSITION_X (CANVAS_SIZE_X / 2)
#define EVENT_CAPTION_POSITION_Y (CANVAS_SIZE_Y / 2)
#define EVENT_CAPTION_DISPLAYING_TIME (3L * 1000L)
#define EVENT_CAPTION_BLINKING_INTERVAL (500L)

/* Definitions for rendering character */
#define CANVAS_FRAME_RENDERING_CHAR '*'
#define PLAYER_JET_RENDERING_CHAR 'o'
#define PLAYER_BULLET_RENDERING_CHAR '|'
#define TOCHCA_RENDERING_CHAR '='
#define INVADER_RENDERING_CHAR 'x'
#define INVADER_BULLET_RENDERING_CHAR '#'

/* Definitions for color */
#define PLAYER_JET_COLOR (COLOR_CYAN)
#define PLAYER_BULLET_COLOR (COLOR_BLUE)
#define TOCHCA_COLOR (COLOR_RED)
#define COMMANDER_INVADER_COLOR (COLOR_MAGENTA)
#define SENIOR_INVADER_COLOR (COLOR_GREEN)
#define YOUNG_INVADER_COLOR (COLOR_CYAN)
#define LOOKIE_INVADER_COLOR (COLOR_MAGENTA)
#define INVADER_BULLET_COLOR (COLOR_MAGENTA)
#define TITLE_COLOR (COLOR_YELLOW)
#define EVENT_CAPTION_COLOR (COLOR_YELLOW)
#define SCORE_COLOR (COLOR_YELLOW)
#define CREDIT_COLOR (COLOR_YELLOW)
#define CANVAS_FRAME_COLOR (COLOR_YELLOW)

#endif /* INVADERS_CONFIG_H_ */
